[paths]
# Directory containing regional.grid.a and regional.depth.a
topo_dir = /cluster/work/users/annettes/TZ2a0.10/topo/

# Directory for cached OHC NetCDF files and output plots
work_dir = /cluster/work/users/annettes/OHC_test/

# Annual mean input files for each dataset
glorys_dir  = /nird/datapeak/NS9481K/SEACLIM/GLORYS_annual/
new_run_dir = /nird/datapeak/NS9481K/SEACLIM/New_ref_run_annual/
old_run_dir = /nird/datapeak/NS9481K/SEACLIM/Old_ref_run_annual/

# Regional mask file
region_file = /nird/datapeak/NS9481K/SEACLIM/ESM_Masks/NAtlantic_Arctic_regions_generic12_TP2.nc
