OBJS =	cairt.o ccloud.o chumid.o csst.o cuv.o cwind.o cwstde.o\
	dmpdat.o fillup.o inclcc.o intpol.o lcoads.o lecmw2.o\
	lecmwf.o lecmwv.o lherov.o newforc.o newold.o posks2.o\
	rHeRo.o recmw2.o recmwv.o rgrsp.o rlatlon.o rmask.o  \
	rotate.o tecall.o spherdist.o dmpwin.o rcoads.o \
	recmwf.o lamip.o mixairt.o lcoads3.o lecmw3.o rstat.o \
	fillall.o tec1.o tecij.o mercator.o cdepth.o \
	filldepth.o shap2d.o dmp2dtec.o crain.o lrain.o rrain.o \
	gridstab.o cice.o rwalsh.o lwalsh.o intpol2.o

SRC =	cairt.f ccloud.f chumid.f csst.f cuv.f cwind.f cwstde.f\
	dmpdat.f fillup.f inclcc.f intpol.f lcoads.f lecmw2.f\
	lecmwf.f lecmwv.f lherov.f newforc.f newold.f posks2.f\
	rHeRo.f recmw2.f recmwv.f rgrsp.f rlatlon.f mask.f \
	rotate.f tecall.f spherdist.f dmpwin.f rcoads.f \
	recmwf.f lamip.f mixairt.f lcoads3.f lecmw3.f rstat.f \
	fillall.f tec1.f tecij.f mercator.f cdepth.f \
	filldepth.f shap2d.f dmp2dtec.f crain.f lrain.f rrain.f \
	gridstab.f cice.f rwalsh.f lwalsh.f intpol2.f

INC = dimension.h


CF =            xlf90_r
FFLAGS =  -q64 -O2 -qrealsize=8  -qextname -qarch=auto -qtune=auto\
		  -qcache=auto -qmaxmem=-1 -qnosave

LINKFLAGS = -q64 -O2 -qrealsize=8  -qextname -qarch=auto -qtune=auto -qcache=auto \
			-qmaxmem=-1 -qnosave


.f.o:
	$(CF)  -c  -qfixed $(FFLAGS) -o $*.o $*.f


newf:	$(OBJS) 
	$(CF)  -o newf $(LINKFLAGS)  $(OBJS)

$(OBJS):  $(INC)
